# Each Players Games For The Past Few Years

In [110]:
import pandas as pd

In [111]:
df = pd.read_csv('./2021_2022_PPR.csv')

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5843 entries, 0 to 5842
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             5843 non-null   object
 1   PPR                5843 non-null   float64
 2   Day                5843 non-null   object
 3   G#                 5843 non-null   int64
 4   Week               5843 non-null   int64
 5   Season             5843 non-null   int64
 6   Date               5843 non-null   object
 7   Age                5843 non-null   object
 8   Team               5843 non-null   object
 9   Unnamed: 9         2902 non-null   object
 10  Opp                5843 non-null   object
 11  Result             5843 non-null   object
 12  FantPt             5843 non-null   float64
 13  PPR.1              5843 non-null   float64
 14  DKPt               5843 non-null   float64
 15  FDPt               5843 non-null   float64
 16  Pos.               5843 non-null   object
 17  Draft              4408 non-null   object
 18  Player-additional  5843 non-null   object
dtypes: float64(5), int64(3), object(11)
memory usage: 867.4+ KB

In [113]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,Opp,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,TAM,L 29-31,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,CLE,W 33-29,26.10,37.10,40.1,31.6,WR,5-165,HillTy00
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,TEN,W 38-13,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,CLE,W 33-29,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,DET,W 41-33,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00

#scraping for games
url = 'https://www.pro-football-reference.com/players/B/BradTo00/gamelog/'
TB_2021 = pd.read_html(url)[0]

In [114]:
TB_2021

    Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
                    Rk               Year               Date
0                    1               2000         2000-09-03
1                    2               2000         2000-09-11
2                    3               2000         2000-09-17
3                    4               2000         2000-09-24
4                    5               2000         2000-10-01
..                 ...                ...                ...
374                 Rk               Year               Date
375                354               2022         2022-09-11
376                355               2022         2022-09-18
377                356               2022         2022-09-25
378                NaN                NaN          321 Games

    Unnamed: 3_level_0 Unnamed: 4_level_0 Unnamed: 5_level_0  \
                    G#               Week                Age
0                    1                  1                NaN
1                    2                  2                NaN
2                    3                  3                NaN
3                    4                  4                NaN
4                    5                  5                NaN
..                 ...                ...                ...
374                 G#               Week                Age
375                  1                  1             45.039
376                  2                  2             45.046
377                  3                  3             45.053
378                NaN                NaN                NaN

    Unnamed: 6_level_0 Unnamed: 7_level_0 Unnamed: 8_level_0  \
                    Tm Unnamed: 7_level_1                Opp
0                  NWE                NaN                TAM
1                  NWE                  @                NYJ
2                  NWE                NaN                MIN
3                  NWE                  @                MIA
4                  NWE                  @                DEN
..                 ...                ...                ...
374                 Tm                NaN                Opp
375                TAM                  @                DAL
376                TAM                  @                NOR
377                TAM                NaN                GNB
378                NaN                NaN                NaN

    Unnamed: 9_level_0  ...   Punting                     Off. Snaps  \
                Result  ...       Yds       Y/P      Blck        Num
0              L 16-21  ...  Inactive  Inactive  Inactive   Inactive
1              L 19-20  ...  Inactive  Inactive  Inactive   Inactive
2              L 13-21  ...  Inactive  Inactive  Inactive   Inactive
3               L 3-10  ...  Inactive  Inactive  Inactive   Inactive
4              W 28-19  ...  Inactive  Inactive  Inactive   Inactive
..                 ...  ...       ...       ...       ...        ...
374             Result  ...       Yds       Y/P      Blck        Num
375             W 19-3  ...         0       NaN         0         62
376            W 20-10  ...         0       NaN         0         67
377            L 12-14  ...         0       NaN         0         65
378           245-76-0  ...        68     34.00         0        NaN

              Def. Snaps            ST Snaps           Unnamed: 51_level_0
          Pct        Num       Pct       Num       Pct              Status
0    Inactive   Inactive  Inactive  Inactive  Inactive            Inactive
1    Inactive   Inactive  Inactive  Inactive  Inactive            Inactive
2    Inactive   Inactive  Inactive  Inactive  Inactive            Inactive
3    Inactive   Inactive  Inactive  Inactive  Inactive            Inactive
4    Inactive   Inactive  Inactive  Inactive  Inactive            Inactive
..        ...        ...       ...       ...       ...                 ...
374       Pct        Num       Pct       Num       Pct              Status
375      100%          0        0%         0        0%                 NaN
376      100%          0        0%         0        0%                 NaN
377      100%          0        0%         0        0%                 NaN
378       NaN        NaN       NaN       NaN       NaN                 NaN

[379 rows x 52 columns]

In [115]:
#Filters to pull a specific player

#player_filter = df.Player = ''
# EX:
player_filter = df[df.Player == 'Amari Cooper']

In [116]:
player_filter

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,Opp,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional
0,Amari Cooper,38.9,Thu,1,1,2021,2021-09-09,27-084,DAL,@,TAM,L 29-31,25.9,38.9,41.9,32.4,WR,1-4,CoopAm00
523,Amari Cooper,5.4,Sun,2,2,2021,2021-09-19,27-094,DAL,@,LAC,W 20-17,2.4,5.4,5.4,3.9,WR,1-4,CoopAm00
846,Amari Cooper,5.6,Mon,3,3,2021,2021-09-27,27-102,DAL,NaN,PHI,W 41-21,2.6,5.6,5.6,4.1,WR,1-4,CoopAm00
1056,Amari Cooper,15.9,Sun,4,4,2021,2021-10-03,27-108,DAL,NaN,CAR,W 36-28,12.9,15.9,15.9,14.4,WR,1-4,CoopAm00
1383,Amari Cooper,15.0,Sun,5,5,2021,2021-10-10,27-115,DAL,NaN,NYG,W 44-20,12.0,15.0,15.0,13.5,WR,1-4,CoopAm00
1748,Amari Cooper,10.5,Sun,6,6,2021,2021-10-17,27-122,DAL,@,NWE,W 35-29 (OT),5.5,10.5,10.5,8.0,WR,1-4,CoopAm00
2211,Amari Cooper,26.2,Sun,7,8,2021,2021-10-31,27-136,DAL,@,MIN,W 20-16,18.2,26.2,29.2,22.2,WR,1-4,CoopAm00
2691,Amari Cooper,5.7,Sun,8,9,2021,2021-11-07,27-143,DAL,NaN,DEN,L 16-30,3.7,5.7,5.7,4.7,WR,1-4,CoopAm00
2915,Amari Cooper,9.1,Sun,9,10,2021,2021-11-14,27-150,DAL,NaN,ATL,W 43-3,5.1,9.1,9.1,7.1,WR,1-4,CoopAm00
3879,Amari Cooper,6.1,Thu,12,13,2021,2021-12-02,27-168,DAL,@,NOR,W 27-17,4.1,6.1,6.1,5.1,WR,1-4,CoopAm00
4060,Amari Cooper,16.1,Sun,13,14,2021,2021-12-12,27-178,DAL,@,WAS,W 27-20,11.1,16.1,16.1,13.6,WR,1-4,CoopAm00
4531,Amari Cooper,2.8,Sun,14,15,2021,2021-12-19,27-185,DAL,@,NYG,W 21-6,0.8,2.8,2.8,1.8,WR,1-4,CoopAm00
4624,Amari Cooper,21.5,Sun,15,16,2021,2021-12-26,27-192,DAL,NaN,WAS,W 56-14,14.5,21.5,21.5,18.0,WR,1-4,CoopAm00
5032,Amari Cooper,10.8,Sun,16,17,2021,2022-01-02,27-199,DAL,NaN,ARI,L 22-25,7.8,10.8,10.8,9.3,WR,1-4,CoopAm00
5461,Amari Cooper,4.7,Sun,1,1,2022,2022-09-11,28-086,CLE,@,CAR,W 26-24,1.7,4.7,4.7,3.2,WR,1-4,CoopAm00
5566,Amari Cooper,25.1,Sun,2,2,2022,2022-09-18,28-093,CLE,NaN,NYJ,L 30-31,16.1,25.1,28.1,20.6,WR,1-4,CoopAm00

In [117]:
df['Home'] = df['Unnamed: 9'].apply(lambda x: 0 if x == '@' else 1)

In [118]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,Opp,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,TAM,L 29-31,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00,0
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,CLE,W 33-29,26.10,37.10,40.1,31.6,WR,5-165,HillTy00,1
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,TEN,W 38-13,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00,0
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,CLE,W 33-29,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00,1
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,DET,W 41-33,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00,0

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5843 entries, 0 to 5842
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             5843 non-null   object
 1   PPR                5843 non-null   float64
 2   Day                5843 non-null   object
 3   G#                 5843 non-null   int64
 4   Week               5843 non-null   int64
 5   Season             5843 non-null   int64
 6   Date               5843 non-null   object
 7   Age                5843 non-null   object
 8   Team               5843 non-null   object
 9   Unnamed: 9         2902 non-null   object
 10  Opp                5843 non-null   object
 11  Result             5843 non-null   object
 12  FantPt             5843 non-null   float64
 13  PPR.1              5843 non-null   float64
 14  DKPt               5843 non-null   float64
 15  FDPt               5843 non-null   float64
 16  Pos.               5843 non-null   object
 17  Draft              4408 non-null   object
 18  Player-additional  5843 non-null   object
 19  Home               5843 non-null   int64
dtypes: float64(5), int64(4), object(11)
memory usage: 913.1+ KB

In [90]:
df['Unnamed: 9'].value_counts()

@    2902
Name: Unnamed: 9, dtype: int64

In [91]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,Opp,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,TAM,L 29-31,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00,0
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,CLE,W 33-29,26.10,37.10,40.1,31.6,WR,5-165,HillTy00,1
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,TEN,W 38-13,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00,0
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,CLE,W 33-29,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00,1
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,DET,W 41-33,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00,0

In [122]:
df.Team.value_counts().sort_index(ascending=True)

ARI    175
ATL    186
BAL    180
BUF    181
CAR    173
CHI    168
CIN    173
CLE    182
DAL    179
DEN    173
DET    173
GNB    188
HOU    191
IND    183
JAX    178
KAN    206
LAC    200
LAR    162
LVR    188
MIA    199
MIN    174
NOR    184
NWE    192
NYG    183
NYJ    191
PHI    170
PIT    175
SEA    180
SFO    180
TAM    191
TEN    196
WAS    189
Name: Team, dtype: int64

In [93]:
#Domed Stadiums
Dome_Dict = {
    "ARI" : 1,
    "ATL" : 1,
    "DAL" : 1,
    "DET" : 1,
    "HOU" : 1,
    "IND" : 1,
    "LAC" : 1,
    "LAR" : 1,
    "LVR" : 1,
    "MIN" : 1,
    "NOR" : 1,
}

In [94]:
#Dome Game
df['Dome_Home'] = df['Team'].apply(lambda x: 1 if x in Dome_Dict.keys() else 0)
df['Dome_Away'] = df['Opp'].apply(lambda x: 1 if x in Dome_Dict.keys() else 0)

In [95]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,...,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home,Dome_Home,Dome_Away
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,...,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00,0,1,0
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,...,26.10,37.10,40.1,31.6,WR,5-165,HillTy00,1,0,0
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,...,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00,0,1,0
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,...,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00,1,0,0
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,...,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00,0,0,1

In [97]:
df['Dome'] = df['Dome_Home'] + df['Dome_Away']

In [98]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,...,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home,Dome_Home,Dome_Away,Dome
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,...,38.90,41.9,32.4,WR,1-4,CoopAm00,0,1,0,1
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,...,37.10,40.1,31.6,WR,5-165,HillTy00,1,0,0,0
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,...,33.56,34.6,34.6,QB,1-1,MurrKy00,0,1,0,1
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,...,33.28,36.3,33.3,QB,1-10,MahoPa00,1,0,0,0
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,...,31.90,35.9,27.4,WR,2-36,SamuDe00,0,0,1,1

In [ ]:
#
Day
Date(Month)
Age
Team
Opp 
Home
Dome
Pos
Draft?

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5843 entries, 0 to 5842
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             5843 non-null   object
 1   PPR                5843 non-null   float64
 2   Day                5843 non-null   object
 3   G#                 5843 non-null   int64
 4   Week               5843 non-null   int64
 5   Season             5843 non-null   int64
 6   Date               5843 non-null   object
 7   Age                5843 non-null   object
 8   Team               5843 non-null   object
 9   Unnamed: 9         2902 non-null   object
 10  Opp                5843 non-null   object
 11  Result             5843 non-null   object
 12  FantPt             5843 non-null   float64
 13  PPR.1              5843 non-null   float64
 14  DKPt               5843 non-null   float64
 15  FDPt               5843 non-null   float64
 16  Pos.               5843 non-null   object
 17  Draft              4408 non-null   object
 18  Player-additional  5843 non-null   object
 19  Home               5843 non-null   int64
 20  Dome               5843 non-null   int64
dtypes: float64(5), int64(5), object(11)
memory usage: 958.7+ KB

In [108]:
df['Player'].value_counts()

Kendrick Bourne     18
Ezekiel Elliott     18
Courtland Sutton    18
Carson Wentz        18
Joe Mixon           18
                    ..
Simi Fehoko          1
Kyle Philips         1
Nick Mullens         1
Keith Kirkwood       1
Pat Elflein          1
Name: Player, Length: 739, dtype: int64

In [99]:
df.drop(['Dome_Home', 'Dome_Away'], axis=1, inplace=True)

In [100]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,...,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home,Dome
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,...,L 29-31,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00,0,1
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,...,W 33-29,26.10,37.10,40.1,31.6,WR,5-165,HillTy00,1,0
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,...,W 38-13,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00,0,1
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,...,W 33-29,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00,1,0
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,...,W 41-33,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00,0,1

# Defense by rank that week

In [ ]:
#level up by pass/run def or by player ranking that week

# Other Factors

In [ ]:
#Home/Away