# Each Players Games For The Past Few Years

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./2021_2022_PPR.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5843 entries, 0 to 5842
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             5843 non-null   object
 1   PPR                5843 non-null   float64
 2   Day                5843 non-null   object
 3   G#                 5843 non-null   int64
 4   Week               5843 non-null   int64
 5   Season             5843 non-null   int64
 6   Date               5843 non-null   object
 7   Age                5843 non-null   object
 8   Team               5843 non-null   object
 9   Unnamed: 9         2902 non-null   object
 10  Opp                5843 non-null   object
 11  Result             5843 non-null   object
 12  FantPt             5843 non-null   float64
 13  PPR.1              5843 non-null   float64
 14  DKPt               5843 non-null   float64
 15  FDPt               5843 non-null   float64
 16  Pos.               5843 non-null   object
 17  Draft              4408 non-null   object
 18  Player-additional  5843 non-null   object
dtypes: float64(5), int64(3), object(11)
memory usage: 867.4+ KB

In [4]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,Opp,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,TAM,L 29-31,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,CLE,W 33-29,26.10,37.10,40.1,31.6,WR,5-165,HillTy00
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,TEN,W 38-13,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,CLE,W 33-29,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,DET,W 41-33,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00

#scraping for games
url = 'https://www.pro-football-reference.com/players/B/BradTo00/gamelog/'
TB_2021 = pd.read_html(url)[0]

In [40]:
tb = pd.read_csv('./Tom_Brady.csv')

In [41]:
tb.tail(18)

,Rk,Year,Date,G#,Week,Age,Tm,Unnamed: 7,Opp,Result,...,Yds.5,Y/P,Blck,Num,Pct,Num.1,Pct.1,Num.2,Pct.2,Status
338,339,2021,2021-09-26,3,3,44,TAM,0.0,LAR,L 24-34,...,0.0,NaN,0.0,73.0,100%,0.0,0%,0.0,0%,NaN
339,340,2021,2021-10-03,4,4,44,TAM,0.0,NWE,W 19-17,...,0.0,NaN,0.0,78.0,100%,0.0,0%,0.0,0%,NaN
340,341,2021,2021-10-10,5,5,44,TAM,NaN,MIA,W 45-17,...,0.0,NaN,0.0,62.0,84%,0.0,0%,0.0,0%,NaN
341,342,2021,2021-10-14,6,6,44,TAM,0.0,PHI,W 28-22,...,0.0,NaN,0.0,75.0,100%,0.0,0%,0.0,0%,NaN
342,343,2021,2021-10-24,7,7,44,TAM,NaN,CHI,W 38-3,...,0.0,NaN,0.0,65.0,89%,0.0,0%,0.0,0%,NaN
343,344,2021,2021-10-31,8,8,44,TAM,0.0,NOR,L 27-36,...,0.0,NaN,0.0,61.0,100%,0.0,0%,0.0,0%,NaN
344,345,2021,2021-11-14,9,10,44,TAM,0.0,WAS,L 19-29,...,0.0,NaN,0.0,48.0,100%,0.0,0%,0.0,0%,NaN
345,346,2021,2021-11-22,10,11,44,TAM,NaN,NYG,W 30-10,...,0.0,NaN,0.0,69.0,88%,0.0,0%,0.0,0%,NaN
346,347,2021,2021-11-28,11,12,44,TAM,0.0,IND,W 38-31,...,0.0,NaN,0.0,67.0,100%,0.0,0%,0.0,0%,NaN
347,348,2021,2021-12-05,12,13,44,TAM,0.0,ATL,W 30-17,...,0.0,NaN,0.0,70.0,100%,0.0,0%,0.0,0%,NaN
348,349,2021,2021-12-12,13,14,44,TAM,NaN,BUF,W 33-27,...,0.0,NaN,0.0,83.0,100%,0.0,0%,0.0,0%,NaN
349,350,2021,2021-12-19,14,15,44,TAM,NaN,NOR,L 0-9,...,0.0,NaN,0.0,74.0,100%,0.0,0%,0.0,0%,NaN
350,351,2021,2021-12-26,15,16,44,TAM,0.0,CAR,W 32-6,...,0.0,NaN,0.0,64.0,96%,0.0,0%,0.0,0%,NaN
351,352,2021,2022-01-02,16,17,44,TAM,0.0,NYJ,W 28-24,...,0.0,NaN,0.0,74.0,100%,0.0,0%,0.0,0%,NaN
352,353,2021,2022-01-09,17,18,44,TAM,NaN,CAR,W 41-17,...,0.0,NaN,0.0,51.0,85%,0.0,0%,0.0,0%,NaN
353,354,2022,2022-09-11,1,1,45,TAM,0.0,DAL,W 19-3,...,0.0,NaN,0.0,62.0,100%,0.0,0%,0.0,0%,NaN
354,355,2022,2022-09-18,2,2,45,TAM,0.0,NOR,W 20-10,...,0.0,NaN,0.0,67.0,100%,0.0,0%,0.0,0%,NaN
355,356,2022,2022-09-25,3,3,45,TAM,NaN,GNB,L 12-14,...,0.0,NaN,0.0,65.0,100%,0.0,0%,0.0,0%,NaN

In [47]:
tb2 = tb[tb.Date > '2021-09-01']

In [48]:
tb2

,Rk,Year,Date,G#,Week,Age,Tm,Unnamed: 7,Opp,Result,...,Yds.5,Y/P,Blck,Num,Pct,Num.1,Pct.1,Num.2,Pct.2,Status
272,273,2017,2017-09-07,1,1,40,NWE,NaN,KAN,L 27-42,...,0.0,NaN,0.0,81.0,100%,0.0,0%,0.0,0%,NaN
273,274,2017,2017-09-17,2,2,40,NWE,0.0,NOR,W 36-20,...,0.0,NaN,0.0,76.0,100%,0.0,0%,0.0,0%,NaN
274,275,2017,2017-09-24,3,3,40,NWE,NaN,HOU,W 36-33,...,0.0,NaN,0.0,64.0,100%,0.0,0%,0.0,0%,NaN
275,276,2017,2017-10-01,4,4,40,NWE,NaN,CAR,L 30-33,...,0.0,NaN,0.0,70.0,100%,0.0,0%,0.0,0%,NaN
276,277,2017,2017-10-05,5,5,40,NWE,0.0,TAM,W 19-14,...,0.0,NaN,0.0,74.0,100%,0.0,0%,0.0,0%,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,352,2021,2022-01-02,16,17,44,TAM,0.0,NYJ,W 28-24,...,0.0,NaN,0.0,74.0,100%,0.0,0%,0.0,0%,NaN
352,353,2021,2022-01-09,17,18,44,TAM,NaN,CAR,W 41-17,...,0.0,NaN,0.0,51.0,85%,0.0,0%,0.0,0%,NaN
353,354,2022,2022-09-11,1,1,45,TAM,0.0,DAL,W 19-3,...,0.0,NaN,0.0,62.0,100%,0.0,0%,0.0,0%,NaN
354,355,2022,2022-09-18,2,2,45,TAM,0.0,NOR,W 20-10,...,0.0,NaN,0.0,67.0,100%,0.0,0%,0.0,0%,NaN
355,356,2022,2022-09-25,3,3,45,TAM,NaN,GNB,L 12-14,...,0.0,NaN,0.0,65.0,100%,0.0,0%,0.0,0%,NaN

In [46]:
#Filters to pull a specific player

#player_filter = df.Player = ''
# EX:
player_filter = df[df.Player == 'Tom Brady']

In [7]:
player_filter

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,Opp,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional
12,Tom Brady,27.16,Thu,1,1,2021,2021-09-09,44-037,TAM,NaN,DAL,W 31-29,27.16,27.16,32.2,29.2,QB,6-199,BradTo00
335,Tom Brady,29.64,Sun,2,2,2021,2021-09-19,44-047,TAM,NaN,ATL,W 48-25,29.64,29.64,30.6,29.6,QB,6-199,BradTo00
662,Tom Brady,28.68,Sun,3,3,2021,2021-09-26,44-054,TAM,@,LAR,L 24-34,28.68,28.68,31.7,28.7,QB,6-199,BradTo00
1093,Tom Brady,11.06,Sun,4,4,2021,2021-10-03,44-061,TAM,@,NWE,W 19-17,11.06,11.06,11.1,11.1,QB,6-199,BradTo00
1313,Tom Brady,37.74,Sun,5,5,2021,2021-10-10,44-068,TAM,NaN,MIA,W 45-17,37.74,37.74,40.7,37.7,QB,6-199,BradTo00
1687,Tom Brady,17.98,Thu,6,6,2021,2021-10-14,44-072,TAM,@,PHI,W 28-22,17.98,17.98,19.0,19.0,QB,6-199,BradTo00
1938,Tom Brady,24.44,Sun,7,7,2021,2021-10-24,44-082,TAM,NaN,CHI,W 38-3,24.44,24.44,24.4,24.4,QB,6-199,BradTo00
2215,Tom Brady,25.20,Sun,8,8,2021,2021-10-31,44-089,TAM,@,NOR,L 27-36,25.20,25.20,31.2,27.2,QB,6-199,BradTo00
2874,Tom Brady,13.00,Sun,9,10,2021,2021-11-14,44-103,TAM,@,WAS,L 19-29,13.00,13.00,15.0,15.0,QB,6-199,BradTo00
3135,Tom Brady,19.28,Mon,10,11,2021,2021-11-22,44-111,TAM,NaN,NYG,W 30-10,19.28,19.28,23.3,20.3,QB,6-199,BradTo00
3508,Tom Brady,11.24,Sun,11,12,2021,2021-11-28,44-117,TAM,@,IND,W 38-31,11.24,11.24,12.2,12.2,QB,6-199,BradTo00
3736,Tom Brady,28.62,Sun,12,13,2021,2021-12-05,44-124,TAM,@,ATL,W 30-17,28.62,28.62,32.6,29.6,QB,6-199,BradTo00
4012,Tom Brady,30.12,Sun,13,14,2021,2021-12-12,44-131,TAM,NaN,BUF,W 33-27 (OT),30.12,30.12,33.1,30.1,QB,6-199,BradTo00
4488,Tom Brady,4.76,Sun,14,15,2021,2021-12-19,44-138,TAM,NaN,NOR,L 0-9,4.76,4.76,6.8,5.8,QB,6-199,BradTo00
4665,Tom Brady,14.38,Sun,15,16,2021,2021-12-26,44-145,TAM,@,CAR,W 32-6,14.38,14.38,14.4,14.4,QB,6-199,BradTo00
4935,Tom Brady,26.40,Sun,16,17,2021,2022-01-02,44-152,TAM,@,NYJ,W 28-24,26.40,26.40,30.4,27.4,QB,6-199,BradTo00
5361,Tom Brady,10.38,Sun,1,1,2022,2022-09-11,45-039,TAM,@,DAL,W 19-3,10.38,10.38,11.4,11.4,QB,6-199,BradTo00
5667,Tom Brady,9.40,Sun,2,2,2022,2022-09-18,45-046,TAM,@,NOR,W 20-10,9.40,9.40,10.4,9.4,QB,6-199,BradTo00

In [38]:
tb3 = tb2.merge(player_filter[['Date','PPR']], left_on='Date', right_on='Date', how='left')

In [39]:
tb3.tail(18)

,Rk,Year,Date,G#,Week,Age,Tm,Unnamed: 7,Opp,Result,...,Y/P,Blck,Num,Pct,Num.1,Pct.1,Num.2,Pct.2,Status,PPR
338,339,2021,2021-09-26,3,3,44,TAM,0.0,LAR,L 24-34,...,NaN,0.0,73.0,100%,0.0,0%,0.0,0%,NaN,28.68
339,340,2021,2021-10-03,4,4,44,TAM,0.0,NWE,W 19-17,...,NaN,0.0,78.0,100%,0.0,0%,0.0,0%,NaN,11.06
340,341,2021,2021-10-10,5,5,44,TAM,NaN,MIA,W 45-17,...,NaN,0.0,62.0,84%,0.0,0%,0.0,0%,NaN,37.74
341,342,2021,2021-10-14,6,6,44,TAM,0.0,PHI,W 28-22,...,NaN,0.0,75.0,100%,0.0,0%,0.0,0%,NaN,17.98
342,343,2021,2021-10-24,7,7,44,TAM,NaN,CHI,W 38-3,...,NaN,0.0,65.0,89%,0.0,0%,0.0,0%,NaN,24.44
343,344,2021,2021-10-31,8,8,44,TAM,0.0,NOR,L 27-36,...,NaN,0.0,61.0,100%,0.0,0%,0.0,0%,NaN,25.20
344,345,2021,2021-11-14,9,10,44,TAM,0.0,WAS,L 19-29,...,NaN,0.0,48.0,100%,0.0,0%,0.0,0%,NaN,13.00
345,346,2021,2021-11-22,10,11,44,TAM,NaN,NYG,W 30-10,...,NaN,0.0,69.0,88%,0.0,0%,0.0,0%,NaN,19.28
346,347,2021,2021-11-28,11,12,44,TAM,0.0,IND,W 38-31,...,NaN,0.0,67.0,100%,0.0,0%,0.0,0%,NaN,11.24
347,348,2021,2021-12-05,12,13,44,TAM,0.0,ATL,W 30-17,...,NaN,0.0,70.0,100%,0.0,0%,0.0,0%,NaN,28.62
348,349,2021,2021-12-12,13,14,44,TAM,NaN,BUF,W 33-27,...,NaN,0.0,83.0,100%,0.0,0%,0.0,0%,NaN,30.12
349,350,2021,2021-12-19,14,15,44,TAM,NaN,NOR,L 0-9,...,NaN,0.0,74.0,100%,0.0,0%,0.0,0%,NaN,4.76
350,351,2021,2021-12-26,15,16,44,TAM,0.0,CAR,W 32-6,...,NaN,0.0,64.0,96%,0.0,0%,0.0,0%,NaN,14.38
351,352,2021,2022-01-02,16,17,44,TAM,0.0,NYJ,W 28-24,...,NaN,0.0,74.0,100%,0.0,0%,0.0,0%,NaN,26.40
352,353,2021,2022-01-09,17,18,44,TAM,NaN,CAR,W 41-17,...,NaN,0.0,51.0,85%,0.0,0%,0.0,0%,NaN,NaN
353,354,2022,2022-09-11,1,1,45,TAM,0.0,DAL,W 19-3,...,NaN,0.0,62.0,100%,0.0,0%,0.0,0%,NaN,10.38
354,355,2022,2022-09-18,2,2,45,TAM,0.0,NOR,W 20-10,...,NaN,0.0,67.0,100%,0.0,0%,0.0,0%,NaN,9.40
355,356,2022,2022-09-25,3,3,45,TAM,NaN,GNB,L 12-14,...,NaN,0.0,65.0,100%,0.0,0%,0.0,0%,NaN,NaN

In [117]:
df['Home'] = df['Unnamed: 9'].apply(lambda x: 0 if x == '@' else 1)

In [118]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,Opp,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,TAM,L 29-31,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00,0
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,CLE,W 33-29,26.10,37.10,40.1,31.6,WR,5-165,HillTy00,1
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,TEN,W 38-13,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00,0
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,CLE,W 33-29,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00,1
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,DET,W 41-33,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00,0

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5843 entries, 0 to 5842
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             5843 non-null   object
 1   PPR                5843 non-null   float64
 2   Day                5843 non-null   object
 3   G#                 5843 non-null   int64
 4   Week               5843 non-null   int64
 5   Season             5843 non-null   int64
 6   Date               5843 non-null   object
 7   Age                5843 non-null   object
 8   Team               5843 non-null   object
 9   Unnamed: 9         2902 non-null   object
 10  Opp                5843 non-null   object
 11  Result             5843 non-null   object
 12  FantPt             5843 non-null   float64
 13  PPR.1              5843 non-null   float64
 14  DKPt               5843 non-null   float64
 15  FDPt               5843 non-null   float64
 16  Pos.               5843 non-null   object
 17  Draft              4408 non-null   object
 18  Player-additional  5843 non-null   object
 19  Home               5843 non-null   int64
dtypes: float64(5), int64(4), object(11)
memory usage: 913.1+ KB

In [90]:
df['Unnamed: 9'].value_counts()

@    2902
Name: Unnamed: 9, dtype: int64

In [91]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,Opp,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,TAM,L 29-31,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00,0
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,CLE,W 33-29,26.10,37.10,40.1,31.6,WR,5-165,HillTy00,1
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,TEN,W 38-13,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00,0
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,CLE,W 33-29,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00,1
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,DET,W 41-33,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00,0

In [122]:
df.Team.value_counts().sort_index(ascending=True)

ARI    175
ATL    186
BAL    180
BUF    181
CAR    173
CHI    168
CIN    173
CLE    182
DAL    179
DEN    173
DET    173
GNB    188
HOU    191
IND    183
JAX    178
KAN    206
LAC    200
LAR    162
LVR    188
MIA    199
MIN    174
NOR    184
NWE    192
NYG    183
NYJ    191
PHI    170
PIT    175
SEA    180
SFO    180
TAM    191
TEN    196
WAS    189
Name: Team, dtype: int64

In [93]:
#Domed Stadiums
Dome_Dict = {
    "ARI" : 1,
    "ATL" : 1,
    "DAL" : 1,
    "DET" : 1,
    "HOU" : 1,
    "IND" : 1,
    "LAC" : 1,
    "LAR" : 1,
    "LVR" : 1,
    "MIN" : 1,
    "NOR" : 1,
}

In [94]:
#Dome Game
df['Dome_Home'] = df['Team'].apply(lambda x: 1 if x in Dome_Dict.keys() else 0)
df['Dome_Away'] = df['Opp'].apply(lambda x: 1 if x in Dome_Dict.keys() else 0)

In [95]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,...,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home,Dome_Home,Dome_Away
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,...,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00,0,1,0
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,...,26.10,37.10,40.1,31.6,WR,5-165,HillTy00,1,0,0
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,...,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00,0,1,0
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,...,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00,1,0,0
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,...,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00,0,0,1

In [97]:
df['Dome'] = df['Dome_Home'] + df['Dome_Away']

In [98]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,...,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home,Dome_Home,Dome_Away,Dome
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,...,38.90,41.9,32.4,WR,1-4,CoopAm00,0,1,0,1
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,...,37.10,40.1,31.6,WR,5-165,HillTy00,1,0,0,0
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,...,33.56,34.6,34.6,QB,1-1,MurrKy00,0,1,0,1
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,...,33.28,36.3,33.3,QB,1-10,MahoPa00,1,0,0,0
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,...,31.90,35.9,27.4,WR,2-36,SamuDe00,0,0,1,1

In [ ]:
#
Day
Date(Month)
Age
Team
Opp 
Home
Dome
Pos
Draft?

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5843 entries, 0 to 5842
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             5843 non-null   object
 1   PPR                5843 non-null   float64
 2   Day                5843 non-null   object
 3   G#                 5843 non-null   int64
 4   Week               5843 non-null   int64
 5   Season             5843 non-null   int64
 6   Date               5843 non-null   object
 7   Age                5843 non-null   object
 8   Team               5843 non-null   object
 9   Unnamed: 9         2902 non-null   object
 10  Opp                5843 non-null   object
 11  Result             5843 non-null   object
 12  FantPt             5843 non-null   float64
 13  PPR.1              5843 non-null   float64
 14  DKPt               5843 non-null   float64
 15  FDPt               5843 non-null   float64
 16  Pos.               5843 non-null   object
 17  Draft              4408 non-null   object
 18  Player-additional  5843 non-null   object
 19  Home               5843 non-null   int64
 20  Dome               5843 non-null   int64
dtypes: float64(5), int64(5), object(11)
memory usage: 958.7+ KB

In [108]:
df['Player'].value_counts()

Kendrick Bourne     18
Ezekiel Elliott     18
Courtland Sutton    18
Carson Wentz        18
Joe Mixon           18
                    ..
Simi Fehoko          1
Kyle Philips         1
Nick Mullens         1
Keith Kirkwood       1
Pat Elflein          1
Name: Player, Length: 739, dtype: int64

In [99]:
df.drop(['Dome_Home', 'Dome_Away'], axis=1, inplace=True)

In [100]:
df.head()

,Player,PPR,Day,G#,Week,Season,Date,Age,Team,Unnamed: 9,...,Result,FantPt,PPR.1,DKPt,FDPt,Pos.,Draft,Player-additional,Home,Dome
0,Amari Cooper,38.90,Thu,1,1,2021,2021-09-09,27-084,DAL,@,...,L 29-31,25.90,38.90,41.9,32.4,WR,1-4,CoopAm00,0,1
1,Tyreek Hill,37.10,Sun,1,1,2021,2021-09-12,27-195,KAN,NaN,...,W 33-29,26.10,37.10,40.1,31.6,WR,5-165,HillTy00,1,0
2,Kyler Murray,33.56,Sun,1,1,2021,2021-09-12,24-036,ARI,@,...,W 38-13,33.56,33.56,34.6,34.6,QB,1-1,MurrKy00,0,1
3,Patrick Mahomes,33.28,Sun,1,1,2021,2021-09-12,25-360,KAN,NaN,...,W 33-29,33.28,33.28,36.3,33.3,QB,1-10,MahoPa00,1,0
4,Deebo Samuel,31.90,Sun,1,1,2021,2021-09-12,25-240,SFO,@,...,W 41-33,22.90,31.90,35.9,27.4,WR,2-36,SamuDe00,0,1

# Defense by rank that week

In [ ]:
#level up by pass/run def or by player ranking that week

# Other Factors

In [ ]:
#Home/Away